import './style.css';
import template from '../cloud-config.example.json';
let runtime={};try{const r=await fetch('/runtime-config.json',{cache:'no-store'});if(r.ok)runtime=await r.json();}catch{}
const defaults={...template,...runtime};
import {zip,strToU8} from 'fflate';
import {Connections,MemoryProvider,LocalProvider,SupabaseProvider,DriveProvider} from './providers.js';
import {bytes,tokenize,joinPath,parentPath,copyName,selectedEntries,checkAbort,isAbort} from './core.js';

const $=id=>document.getElementById(id);
const escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const icon=(name)=>`<img src="/assets/icons/${name}.png" alt="" class="icon">`;
let overrides={};try{overrides=JSON.parse(localStorage.getItem('nightcopy-settings')||'{}')}catch{}
let config={...defaults,...overrides};
const staging=new MemoryProvider();
const panes=[{provider:staging,path:'',entries:[],selected:new Set(),loading:false,history:[]},{provider:null,path:'',entries:[],selected:new Set(),loading:false,history:[]}];
let active=0,view='files',clipboard=null,busy=false,refreshSerial=[0,0],previewUrl=null;
const jobs=[],logs=[],history=[];let historyIndex=0;
let c=new Connections(config,renderConnections);

$('app').innerHTML=`
<div class="console-shell">
 <aside class="sidebar">
  <a class="brand" href="/" aria-label="NightCopy home"><img src="/assets/nightcopy-logo.png" alt="NightCopy skull logo"><span>NIGHT<span class="brand-copy">COPY</span><small>COLETECH SYSTEMS</small></span></a>
  <div class="rail-heading">CONTROL DECK <span>02.00</span></div>
  <nav aria-label="Main navigation"><button data-view="files" class="nav-button active">${icon('folder')}<span>File console</span><kbd>01</kbd></button><button data-view="queue" class="nav-button">${icon('copy')}<span>Transfer queue</span><b id="queueBadge">0</b></button><button data-view="connections" class="nav-button">${icon('satellite')}<span>Connections</span><kbd>03</kbd></button></nav>
  <div class="rail-heading uplink-heading">MOUNTED VOLUMES</div>
  <button class="volume" data-mount="staging"><span class="volume-symbol">C:</span><span><b>Local staging</b><small id="stagingCount">No files loaded</small></span><i class="led cyan"></i></button>
  <button class="volume" data-mount="drive"><span class="volume-symbol">G:</span><span><b>Google Drive</b><small id="driveRail">Not connected</small></span><i id="driveLed" class="led"></i></button>
  <button class="volume" data-mount="supabase"><span class="volume-symbol">S:</span><span><b>Supabase vault</b><small id="sbRail">Checking connection</small></span><i id="sbLed" class="led"></i></button>
  <button class="mount-folder" id="mountLocal">＋ Mount local folder</button>
  <div class="rail-bottom"><div class="signal-bars" aria-hidden="true"><i></i><i></i><i></i><i></i><i></i></div><p>YOUR FILES.<br>YOUR NEXT DESTINATION.</p><span>EST. 1995 / BUILT FOR NOW</span><button class="quiet" id="helpButton">COMMAND REFERENCE ↗</button></div>
 </aside>
 <main>
  <header class="topbar"><div><i class="led cyan"></i><span id="systemStatus">BROWSER STATION READY</span><span class="top-tag">NIGHTCOPY.EXE</span></div><div><span class="host-label" id="hostLabel"></span><time id="clock"></time><button class="avatar" id="accountButton" aria-label="Account and connections">NC</button></div></header>
  <section class="heading"><div><p class="eyebrow">PERSONAL DATA TERMINAL <span>/</span> COLETECH SYSTEMS</p><h1 id="pageTitle">File console<span class="title-caret">_</span></h1><p id="pageSubtitle">Two panes. One command. Keep a copy.</p></div><div class="heading-actions"><button class="button" id="uploadFiles">${icon('upload')} Import files</button><button class="button primary" id="connectDrive">${icon('satellite')} Connect Drive <span>↗</span></button></div></section>
  <nav class="mobile-nav" aria-label="Console navigation"><button data-view="files" class="active">Files</button><button data-view="queue">Queue</button><button data-view="connections">Connections</button></nav>
  <div class="health-strip"><span><i class="led cyan"></i> LOCAL <b id="localStatus">SESSION STORAGE</b></span><span><i id="driveHealth" class="led"></i> GOOGLE DRIVE <b id="driveStatus">OFFLINE</b></span><span><i id="sbHealth" class="led"></i> SUPABASE <b id="sbStatus">CHECKING</b></span><span class="last-health">PROTOCOL <b>HTTPS / DIRECT</b></span></div>
  <section id="filesView" class="view active">
   <div class="workspace-caption"><span><i class="small-square"></i> DUAL-PANE EXPLORER</span><div><button class="quiet" id="swapPanes">⇄ Swap panes</button><button class="quiet" id="refreshPanes">↻ Refresh</button></div></div>
   <div class="explorers">${[0,1].map(i=>`<section class="explorer ${i===0?'focused':''}" id="pane${i}" aria-label="${i===0?'Left':'Right'} file pane"><div class="pane-title"><span><i class="led ${i===0?'cyan':'amber'}"></i><b>${i===0?'LEFT':'RIGHT'}</b><small id="role${i}">${i===0?'SOURCE':'DESTINATION'}</small></span><button class="quiet" data-picker="${i}" aria-label="Choose ${i===0?'left':'right'} location">${icon('folder')} Choose location ↗</button></div><div class="pane-location"><span id="mount${i}">${i===0?'C:':'—'}</span><select id="provider${i}" aria-label="${i===0?'Left':'Right'} storage"><option value="${i===0?'staging':''}">${i===0?'Local staging':'Choose destination'}</option><option value="staging">Local staging</option><option value="local">Mount local folder…</option><option value="drive">Google Drive</option><option value="supabase">Supabase vault</option></select><button class="square" data-up="${i}" aria-label="Go up in ${i===0?'left':'right'} pane">↑</button></div><div class="path-bar"><span>⌁</span><span id="path${i}">/</span></div><label class="pane-search"><span>⌕</span><input id="filter${i}" placeholder="Filter files in this folder…" aria-label="Filter ${i===0?'left':'right'} files"><kbd>/</kbd></label><div class="list-head"><label><input type="checkbox" id="all${i}" aria-label="Select all ${i===0?'left':'right'} files"> NAME</label><span>SIZE</span><span>TYPE</span></div><div id="list${i}" class="file-list"></div><div class="pane-footer"><span id="count${i}">0 items</span><span id="selection${i}">0 selected</span></div></section>`).join('')}</div>
   <div class="operation-bar"><div><span class="operation-direction" id="direction">LEFT → RIGHT</span><small id="operationHint">Select files to prepare a transfer</small></div><div class="operation-buttons"><button class="button" id="copyButton">${icon('copy')} Copy <kbd>F5</kbd></button><button class="button" id="pasteButton" disabled>Paste</button><button class="button" id="duplicateButton">${icon('copy')} Duplicate</button><button class="button" id="downloadButton">${icon('download')} Download</button><button class="button" id="zipButton">${icon('floppy')} ZIP</button><button class="button" id="folderButton">＋ Folder</button><button class="button primary" id="transferButton">Transfer <span>→</span><kbd>F6</kbd></button></div></div>
  </section>
  <section id="queueView" class="view"><div class="queue-toolbar"><span>Sequential jobs · progress from actual bytes</span><button class="button" id="clearJobs">Clear finished jobs</button></div><div id="jobsView"></div></section>
  <section id="connectionsView" class="view"><div class="connection-grid"><article class="connection-card"><div class="card-top">${icon('satellite')}<span class="chip" id="googleChip">NOT CONNECTED</span></div><p class="eyebrow">01 / CLOUD UPLINK</p><h2>Google Drive</h2><p>Browse, upload, download and duplicate files in your archive account.</p><div class="account-readout"><span>ARCHIVE ACCOUNT</span><b id="driveAccount"></b></div><button class="button primary" id="driveLogin">Connect Google Drive ↗</button><button class="quiet" id="driveDisconnect">Disconnect Drive</button><small>Google sign-in opens in a secure Google window. Access lasts for this tab’s session.</small></article><article class="connection-card"><div class="card-top">${icon('vault')}<span class="chip" id="supabaseChip">CHECKING</span></div><p class="eyebrow">02 / PRIVATE VAULT</p><h2>Supabase</h2><p>Use your private file bucket and save a history of completed transfers.</p><div class="account-readout"><span>PROJECT</span><b id="sbProject"></b><small id="sbDetail"></small></div><form id="loginForm"><label>Email<input type="email" id="loginEmail" required autocomplete="username" placeholder="Your Supabase account"></label><label>Password<input type="password" id="loginPassword" required autocomplete="current-password"></label><button class="button primary" id="sbLogin">Sign in to vault →</button></form><button class="button" id="logoutButton" hidden>Sign out of vault</button></article><article class="connection-card setup-card"><div class="card-top">${icon('terminal')}<span class="chip">CONFIGURATION</span></div><p class="eyebrow">03 / STATION SETTINGS</p><h2>Connection setup</h2><p>Public connection settings are saved on this device. Server keys stay out of the browser.</p><form id="settingsForm"><label>Supabase project URL<input id="settingUrl" type="url" required placeholder="https://project.supabase.co"></label><label>Supabase public / publishable key<input id="settingKey" required autocomplete="off" spellcheck="false"></label><label>Private bucket<input id="settingBucket" required value="nightcopy" pattern="[a-zA-Z0-9_-]+"></label><label>Google OAuth web client ID<input id="settingGoogle" placeholder="…apps.googleusercontent.com" spellcheck="false"></label><label>Google Drive account<input id="settingAccount" type="email" required></label><button class="button" type="submit">Save & test connections</button></form><a href="/SETUP.html" target="_blank" rel="noopener" class="quiet">Hosting, OAuth and private storage setup ↗</a></article></div></section>
  <section class="terminal" aria-label="DOS command shell"><div class="terminal-title"><span>${icon('terminal')} NIGHTCOPY COMMAND SHELL <small>MS-DOS INSPIRED / REAL OPERATIONS</small></span><div><button class="quiet" id="terminalHelp">HELP</button><button class="quiet" id="terminalClear" aria-label="Clear terminal">CLEAR</button><button class="square" id="collapseTerminal" aria-expanded="true" aria-label="Collapse terminal">−</button></div></div><div id="terminalBody"><div id="terminalLog" class="terminal-log" role="log" aria-live="polite"></div><form id="terminalForm" autocomplete="off"><label for="commandInput" id="prompt">C:\STAGING&gt;</label><input id="commandInput" placeholder="Type help for commands…" aria-label="DOS command"><button aria-label="Run command">↵</button></form></div></section>
  <footer><span><i class="led cyan"></i> <b id="footerStatus">READY FOR INPUT</b></span><span id="sessionSummary">0 files staged · 0 transfers complete</span><span>NIGHTCOPY v2.0 <span class="footer-dot">◆</span> COLETECH</span></footer>
 </main>
</div>
<input type="file" id="filePicker" multiple hidden><input type="file" id="folderPicker" webkitdirectory multiple hidden><div id="toast" class="toast" role="status" hidden></div>
<dialog id="reviewDialog"><form method="dialog"><p class="eyebrow">OPERATION REVIEW</p><h2 id="reviewTitle"></h2><div id="reviewContent"></div><div class="dialog-actions"><button class="button" value="cancel">Cancel</button><button class="button primary" value="confirm" id="reviewConfirm">Confirm & queue →</button></div></form></dialog>
<dialog id="previewDialog"><div class="preview-header"><h2 id="previewTitle"></h2><button class="button" id="closePreview">Close ×</button></div><div id="previewContent"></div></dialog>
<dialog id="locationDialog"><p class="eyebrow">CHOOSE A VOLUME</p><h2 id="locationTitle">Mount location</h2><div class="mount-options"><button class="button" data-location="local">${icon('folder')} Local folder / USB drive</button><button class="button" data-location="staging">${icon('floppy')} Session file staging</button><button class="button" data-location="drive">${icon('satellite')} Google Drive</button><button class="button" data-location="supabase">${icon('vault')} Supabase private vault</button><button class="quiet" id="importFolder">Import folder into staging</button></div><button class="quiet" id="closeLocation">Cancel</button></dialog>`;

function notify(message,error=false){$('toast').textContent=message;$('toast').classList.toggle('error',error);$('toast').hidden=false;clearTimeout(notify.timer);notify.timer=setTimeout(()=>$('toast').hidden=true,6000);}
function log(message,type='info'){logs.push({message,type,time:new Date().toLocaleTimeString('en-GB')});if(logs.length>250)logs.shift();renderLog();}
function renderLog(){$('terminalLog').innerHTML=logs.map(l=>`<div class="log-line ${l.type}"><time>${l.time}</time><span>${escape(l.message)}</span></div>`).join('');$('terminalLog').scrollTop=$('terminalLog').scrollHeight;}
function guard(fn){return async(...args)=>{try{await fn(...args)}catch(e){if(isAbort(e))return;log(e.message,'error');notify(e.message,true);}}}
function setView(next){view=next;for(const v of ['files','queue','connections'])$(v+'View').classList.toggle('active',v===view);document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===view));$('pageTitle').innerHTML=({'files':'File console','queue':'Transfer queue','connections':'Connections'}[view])+'<span class="title-caret">_</span>';$('pageSubtitle').textContent={files:'Two panes. One command. Keep a copy.',queue:'Every operation. Every byte. A clear record.',connections:'Your archive account. Your private vault.'}[view];}
function renderConnections(){if(!$('sbRail'))return;const signed=!!c.session;const online=!!c.settings;const drive=!!c.driveToken;const sbState=signed?(c.storageReady?'PRIVATE / READY':'SIGNED IN'):online?'SIGN IN':'SETUP REQUIRED';for(const id of ['sbStatus','sbRail','supabaseChip'])$(id).textContent=sbState;for(const id of ['driveStatus','driveRail','googleChip'])$(id).textContent=drive?'CONNECTED':'NOT CONNECTED';for(const id of ['sbLed','sbHealth'])$(id).className='led '+(signed?'cyan':online?'amber':'');for(const id of ['driveLed','driveHealth'])$(id).className='led '+(drive?'cyan':'');$('driveAccount').textContent=c.driveUser?.emailAddress||config.driveAccount;$('connectDrive').innerHTML=icon('satellite')+(drive?' Open Drive':' Connect Drive')+' <span>↗</span>';$('sbProject').textContent=config.supabaseUrl||'No project configured';$('sbDetail').textContent=signed?c.session.user.email:online?'Project reachable · sign in to use your private bucket':'Public connection needs setup';$('loginForm').hidden=signed;$('logoutButton').hidden=!signed;$('driveDisconnect').hidden=!drive;$('localStatus').textContent=panes.some(p=>p.provider?.kind==='local')?'FOLDER MOUNTED':'SESSION STORAGE';}
function renderPane(i){const p=panes[i];const rows=p.entries.filter(e=>e.name.toLowerCase().includes($('filter'+i).value.toLowerCase()));const mount=p.provider?{staging:'C:',local:'L:',drive:'G:',supabase:'S:'}[p.provider.kind]:'—';$('mount'+i).textContent=mount;$('provider'+i).value=p.provider?.kind||'';$('path'+i).textContent='/'+p.path;$('all'+i).checked=!!rows.length&&rows.every(e=>p.selected.has(e.id));$('all'+i).indeterminate=rows.some(e=>p.selected.has(e.id))&&!$('all'+i).checked;
 $('list'+i).innerHTML=p.loading?'<div class="pane-empty"><span class="loading-mark">◌</span><h3>Reading directory</h3><p>Waiting for the actual file listing…</p></div>':!p.provider?`<div class="pane-empty"><div class="empty-glyph">${icon('folder')}</div><h3>Where to next?</h3><p>Choose a local folder, Google Drive<br>or your private Supabase vault.</p><button class="button" data-picker="${i}">＋ Choose destination</button></div>`:p.error?`<div class="pane-empty"><span class="empty-glyph warning">!</span><h3>Connection needs attention</h3><p>${escape(p.error)}</p><button class="button" data-setup>Open connections</button></div>`:!p.entries.length?`<div class="pane-empty"><div class="empty-glyph">${icon(p.provider.kind==='staging'?'upload':'folder')}</div><h3>${p.provider.kind==='staging'?'Your files start here':'An empty directory'}</h3><p>${p.provider.kind==='staging'?'Drop files here or import a folder.<br>Session files stay in this tab until you transfer them.':'Create a folder or transfer files into this location.'}</p>${p.provider.kind==='staging'?'<button class="button" data-import>＋ Import files</button>':''}</div>`:!rows.length?'<div class="pane-empty"><h3>No matching files</h3><p>Try another filter.</p></div>':rows.map(e=>`<div class="file-row ${p.selected.has(e.id)?'selected':''}" data-entry="${escape(e.id)}"><label><input type="checkbox" data-check="${escape(e.id)}" ${p.selected.has(e.id)?'checked':''} aria-label="Select ${escape(e.name)}"></label><button class="file-name" data-open="${escape(e.id)}" title="${escape(e.name)}">${icon(e.directory?'folder':fileIcon(e.name))}<span>${escape(e.name)}</span></button><span class="file-size">${e.directory?'—':bytes(e.bytes)}</span><span class="file-type">${e.directory?'DIR':e.name.split('.').length>1?escape(e.name.split('.').at(-1).toUpperCase().slice(0,5)):'FILE'}</span></div>`).join('');
 $('count'+i).textContent=p.entries.length+' item'+(p.entries.length===1?'':'s');const selected=selectedEntries(p);$('selection'+i).textContent=selected.length+' selected / '+bytes(selected.reduce((n,e)=>n+e.bytes,0));updateActive();
}
function fileIcon(name){return /\.(mp3|wav|ogg|flac)$/i.test(name)?'mail':/\.(zip|7z|rar|gz)$/i.test(name)?'vault':/\.(js|py|html|css|json|txt|md)$/i.test(name)?'terminal':'floppy';}
function updateActive(){
 for(let i=0;i<2;i++){$('pane'+i).classList.toggle('focused',i===active);$('role'+i).textContent=i===active?'SOURCE':'DESTINATION';}
 const p=panes[active];const slash=String.fromCharCode(92);
 $('direction').textContent=active===0?'LEFT → RIGHT':'RIGHT → LEFT';
 const selected=selectedEntries(p);
 $('operationHint').textContent=selected.length?selected.length+' selected · '+bytes(selected.reduce((n,e)=>n+e.bytes,0)):'Select files to prepare a transfer';
 const root=p.provider?{staging:'C:'+slash+'STAGING',local:'L:'+slash+p.provider.label,drive:'G:'+slash+'DRIVE',supabase:'S:'+slash+'VAULT'}[p.provider.kind]:'C:'+slash+'NIGHTCOPY';
 $('prompt').textContent=root+(p.path?slash+p.path.replaceAll('/',slash):'')+'>';
 $('pasteButton').disabled=!clipboard;
 $('stagingCount').textContent=staging.files.size+' files in this tab';
 $('sessionSummary').textContent=staging.files.size+' files staged · '+jobs.filter(j=>j.status==='complete').length+' transfers complete';renderConnections();
}
async function refresh(i){const p=panes[i],serial=++refreshSerial[i];if(!p.provider){p.entries=[];p.loading=false;p.error=null;renderPane(i);return;}p.loading=true;p.error=null;renderPane(i);try{const data=await p.provider.list(p.path);if(serial!==refreshSerial[i])return;p.entries=data;p.selected=new Set([...p.selected].filter(id=>data.some(e=>e.id===id)));}catch(e){if(serial!==refreshSerial[i])return;p.error=e.message;p.entries=[];log(e.message,'error');}finally{if(serial===refreshSerial[i]){p.loading=false;renderPane(i);}}}
async function navigate(i,path){const p=panes[i];p.history.push(p.path);p.path=path;p.selected.clear();await refresh(i);}
async function mount(i,kind){let provider;if(kind==='staging')provider=staging;else if(kind==='local'){if(!window.showDirectoryPicker){notify('This browser needs the folder-import fallback. Imported files can be downloaded or sent to cloud storage.');$('folderPicker').click();return;}try{const h=await window.showDirectoryPicker({mode:'readwrite',id:'nightcopy-pane-'+i});provider=new LocalProvider(h);}catch(e){if(isAbort(e))return;throw e;}}else if(kind==='drive'){if(!c.driveToken){setView('connections');await c.connectDrive();if(!c.driveToken)return;}provider=new DriveProvider(c);}else if(kind==='supabase'){if(!c.session){setView('connections');notify('Sign in to your private Supabase vault first.');return;}provider=new SupabaseProvider(c);}else return;panes[i].provider=provider;panes[i].path='';panes[i].selected.clear();active=i;await refresh(i);log('Mounted '+provider.label+' in '+(i===0?'LEFT':'RIGHT')+' pane.');}
async function openEntry(i,id){active=i;updateActive();const p=panes[i];const e=p.entries.find(x=>x.id===id);if(!e)return;if(e.directory)await navigate(i,await p.provider.enter(e,p.path));else{p.selected.has(id)?p.selected.delete(id):p.selected.add(id);renderPane(i);}}
function chooseFiles(){active=0;$('filePicker').click();}
async function imported(files){if(!files.length)return;staging.import(files);panes[0].provider=staging;panes[0].path='';panes[0].selected.clear();active=0;await refresh(0);if(panes[1].provider===staging)await refresh(1);log('Imported '+files.length+' file(s) into session staging.');notify(files.length+' files ready to copy.');}
let pickerSide=0;
function chooseLocation(i){pickerSide=i;$('locationTitle').textContent='Mount '+(i===0?'left':'right')+' location';$('locationDialog').showModal();}

function snapshot(p){return {provider:p.provider,path:p.path,entries:selectedEntries(p)};}
function requireSelected(){const p=panes[active];if(!p.provider||!p.selected.size)throw Error('Select at least one file or folder first.');return snapshot(p);}
async function review(title,body,confirm='Confirm & queue →'){$('reviewTitle').textContent=title;$('reviewContent').innerHTML=body;$('reviewConfirm').textContent=confirm;$('reviewDialog').returnValue='cancel';$('reviewDialog').showModal();return new Promise(resolve=>$('reviewDialog').addEventListener('close',()=>resolve($('reviewDialog').returnValue==='confirm'),{once:true}));}
async function prepare(mode,source=requireSelected(),dest=snapshot(panes[1-active])){
 if(mode==='duplicate')dest={provider:source.provider,path:source.path};
 if(mode!=='download'&&!dest.provider)throw Error('Choose a destination in the opposite pane first.');
 if(!source.entries.length)throw Error('The clipboard is empty.');
 if(mode==='transfer'&&source.provider.kind===dest.provider?.kind){let same=source.provider===dest.provider;if(source.provider.kind==='local')same=await source.provider.handle.isSameEntry(dest.provider.handle);if(source.provider.kind==='drive'||source.provider.kind==='supabase')same=true;if(same){for(const e of source.entries){const selectedPath=joinPath(source.path,e.name);if(source.path===dest.path||e.directory&&(dest.path===selectedPath||dest.path.startsWith(selectedPath+'/')))throw Error('Choose a destination outside the source folder, or use Duplicate.');}}}
 const names=source.entries.slice(0,10).map(e=>'<li>'+escape(e.name)+(e.directory?' <small>includes its contents</small>':'')+'</li>').join('');
 const target=mode==='download'?'Browser downloads':dest.provider.label+' /'+dest.path;
 if(!await review(mode==='download'?'Download selected files':mode==='duplicate'?'Create a duplicate':mode==='zip'?'Create a ZIP archive':'Review file transfer',`<p class="review-route">${escape(source.provider.label)} <span>→</span> ${escape(target)}</p><ul>${names}</ul>${source.entries.length>10?'<p>and '+(source.entries.length-10)+' more items</p>':''}<p>Originals stay in place. Existing local and vault files receive a new copy name. Drive creates new files.</p>${mode==='download'?'<p>Your browser may ask to allow multiple downloads.</p>':''}`))return;
 enqueue({mode,source,dest});
}
function enqueue(payload){const j={id:crypto.randomUUID(),...payload,title:payload.mode.toUpperCase()+' / '+payload.source.entries.map(e=>e.name).join(', '),status:'queued',done:0,total:0,files:0,message:'Waiting for the next transfer slot',created:new Date().toISOString(),controller:new AbortController()};jobs.unshift(j);log(j.title+' queued.');renderJobs();processQueue();}
async function collect(provider,path,entries,signal,output=[],relative='',depth=0){if(depth>48)throw Error('Folder tree exceeds 48 levels.');for(const e of entries){checkAbort(signal);if(output.length>=10000)throw Error('Selection exceeds 10,000 files. Split the transfer.');const rel=joinPath(relative,e.name);if(e.directory){const sub=await provider.enter(e,path);output.push({directory:true,relative:rel});await collect(provider,sub,await provider.list(sub),signal,output,rel,depth+1);}else output.push({entry:e,relative:rel});}return output;}
function jobProgress(j,done,total){j.done=done;j.total=total;renderJobs();}
async function processQueue(){if(busy)return;const j=[...jobs].reverse().find(j=>j.status==='queued');if(!j)return;busy=true;j.status='running';j.started=performance.now();renderJobs();const signal=j.controller.signal;
 try{
  const collected=await collect(j.source.provider,j.source.path,j.source.entries,signal);const files=collected.filter(e=>!e.directory);j.total=files.reduce((n,f)=>n+f.entry.bytes,0);j.message='Preparing '+files.length+' files';renderJobs();
  if(j.mode==='zip'){await runZip(j,collected,signal);}else{
   const destPaths=new Map([['',j.dest.path]]);const duplicateRoots=new Map();let written=0;
   for(const f of collected){checkAbort(signal);const relativeBits=f.relative.split('/');const parent=relativeBits.slice(0,-1).join('/');let destPath=destPaths.get(parent)||j.dest.path;
    if(f.directory&&j.mode!=='download'){let name=relativeBits.at(-1);if(!parent){const existing=await j.dest.provider.list(destPath);const base=j.mode==='duplicate'?copyName(name):name;name=base;for(let n=1;existing.some(e=>e.name===name);n++)name=copyName(relativeBits.at(-1),n);}const p=await j.dest.provider.mkdir(destPath,name);destPaths.set(f.relative,p);continue;}
    if(f.directory)continue;
    j.message=f.relative;renderJobs();
    if(j.mode==='duplicate'&&j.source.provider.kind==='drive'){await j.source.provider.duplicate(f.entry,destPath,signal);written+=f.entry.bytes;j.files++;jobProgress(j,written,j.total);continue;}
    if(j.source.provider.kind==='supabase'&&f.entry.bytes>config.maxBufferedBytes)throw Error('This cloud file exceeds the browser buffer limit. Use the desktop station.');
    const result=await j.source.provider.read(f.entry,signal);checkAbort(signal);const blob=result.blob;
    if(j.dest.provider?.kind==='supabase'&&blob.size>50*1024*1024)throw Error('Standard vault uploads are limited to 50 MB in this version. Use Drive for larger files.');
    // Native Google document exports have no size until downloaded.
    j.total+=blob.size-f.entry.bytes;
    if(j.mode==='download'){saveBlob(blob,result.name);written+=blob.size;}else{const name=j.mode==='duplicate'&&!parent?copyName(result.name):result.name;await j.dest.provider.write(destPath,name,blob,signal,(done)=>jobProgress(j,written+done,j.total));written+=blob.size;}
    j.files++;jobProgress(j,written,j.total);
   }
  }
  checkAbort(signal);j.status='complete';j.message=j.files+' files complete';j.finished=new Date().toISOString();log(j.title+' COMPLETE / '+bytes(j.done),'success');await saveReceipt(j);
 }catch(e){j.status=isAbort(e)?'stopped':'failed';j.message=e.message;log(j.title+' / '+e.message,isAbort(e)?'info':'error');}finally{busy=false;renderJobs();await Promise.all([refresh(0),refresh(1)]);processQueue();}
}
async function runZip(j,collected,signal){const entries={};let total=0;for(const f of collected){checkAbort(signal);if(f.directory){entries[f.relative+'/']=new Uint8Array();continue;}if(total+f.entry.bytes>config.maxBufferedBytes)throw Error('ZIP selection exceeds 256 MB. Split it or use the desktop station.');const {blob,name}=await j.source.provider.read(f.entry,signal);total+=blob.size;if(total>config.maxBufferedBytes)throw Error('ZIP selection exceeds 256 MB.');j.message=f.relative;const parts=f.relative.split('/');parts[parts.length-1]=name;entries[parts.join('/')]=new Uint8Array(await blob.arrayBuffer());j.files++;jobProgress(j,total,total);}
 let manifest='nightcopy-manifest.json';for(let n=1;entries[manifest];n++)manifest=copyName('nightcopy-manifest.json',n);entries[manifest]=strToU8(JSON.stringify({created:new Date().toISOString(),source:j.source.provider.label,files:Object.keys(entries)},null,2));
 const data=await new Promise((resolve,reject)=>{const terminate=zip(entries,{level:1},(e,d)=>{signal.removeEventListener('abort',abort);if(e)reject(e);else resolve(d);});const abort=()=>{terminate();reject(new DOMException('Stopped by operator','AbortError'));};signal.addEventListener('abort',abort,{once:true});});checkAbort(signal);const blob=new Blob([data],{type:'application/zip'});const name='nightcopy-'+new Date().toISOString().slice(0,19).replaceAll(':','-')+'.zip';if(j.dest.provider)await j.dest.provider.write(j.dest.path,name,blob,signal);else saveBlob(blob,name);j.total=total;j.done=total;}
async function saveReceipt(j){if(!c.session||!c.settings)return;const {error}=await c.sb.from('nightcopy_transfers').insert({id:j.id,user_id:c.session.user.id,operation:j.mode,source:j.source.provider.kind,destination:j.dest.provider?.kind||'download',file_count:j.files,bytes:j.done,status:j.status,created_at:j.created,completed_at:j.finished});if(error)log('Files completed. Cloud transfer-history receipt was not saved: '+error.message,'error');}
function saveBlob(blob,name){const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),60000);}
function renderJobs(){const pending=jobs.filter(j=>['running','queued'].includes(j.status));$('queueBadge').textContent=pending.length;$('footerStatus').textContent=busy?'TRANSFER IN PROGRESS':'READY FOR INPUT';$('jobsView').innerHTML=!jobs.length?'<div class="queue-empty"><span>⇄</span><h2>All channels quiet</h2><p>Select files in the console to start a transfer.</p><button class="button" data-show-files>Open file console →</button></div>':jobs.map(j=>{const percent=j.total?Math.min(100,Math.round(j.done/j.total*100)):j.status==='complete'?100:0;const elapsed=j.started?(performance.now()-j.started)/1000:0;return `<article class="job"><div class="job-icon">${icon(j.mode==='zip'?'floppy':'copy')}</div><div class="job-content"><div class="job-heading"><h3>${escape(j.title)}</h3><span class="chip ${j.status}">${j.status.toUpperCase()}</span></div><p>${escape(j.message)}</p><div class="progress-track"><span style="width:${percent}%"></span></div><div class="job-meta"><span>${bytes(j.done)} / ${bytes(j.total)} <b>${percent}%</b></span><span>${j.status==='running'&&elapsed>0?bytes(j.done/elapsed)+'/s':''}</span><span>${j.files} completed files</span></div></div>${['queued','running'].includes(j.status)?`<button class="button stop" data-stop="${j.id}">Stop</button>`:''}</article>`;}).join('');updateActive();}
async function preview(){const source=requireSelected();if(source.entries.length!==1||source.entries[0].directory)throw Error('Select one file to preview.');const e=source.entries[0];if(e.bytes>5*1024*1024)throw Error('Preview supports files up to 5 MB. Download larger files.');const {blob,name}=await source.provider.read(e);if(blob.size>5*1024*1024)throw Error('Preview file is larger than 5 MB.');$('previewTitle').textContent=name;if(previewUrl)URL.revokeObjectURL(previewUrl);previewUrl=URL.createObjectURL(blob);const ext=name.split('.').at(-1).toLowerCase();if(/^(png|jpg|jpeg|gif|webp|bmp)$/.test(ext))$('previewContent').innerHTML='<img class="preview-image" src="'+previewUrl+'" alt="File preview">';else if(/^(mp3|wav|ogg|flac)$/.test(ext))$('previewContent').innerHTML='<audio controls src="'+previewUrl+'"></audio>';else if(/^(mp4|webm)$/.test(ext))$('previewContent').innerHTML='<video controls src="'+previewUrl+'"></video>';else if(/^(txt|md|json|js|ts|py|html|css|csv|log|xml|svg)$/.test(ext)){$('previewContent').innerHTML='<pre></pre>';$('previewContent').firstChild.textContent=await blob.text();}else $('previewContent').textContent='This file type has no inline preview. Use Download to open it locally.';$('previewDialog').showModal();}
async function newFolder(name){const p=panes[active];if(!p.provider)throw Error('Mount a folder or cloud volume first.');if(!name){const confirmed=await review('Create a folder','<label>Folder name<input id="newFolderName" value="New folder" required pattern="[^/\\\\]+"></label><p>Location: '+escape(p.provider.label+' /'+p.path)+'</p>','Create folder →');if(!confirmed)return;name=$('newFolderName').value;}if(pathPartsSafe(name).length!==1)throw Error('Enter one folder name without slashes.');const already=p.entries.some(e=>e.name===name);if(already)throw Error('That name already exists.');await p.provider.mkdir(p.path,name);log('Created folder '+name);await refresh(active);}
function pathPartsSafe(path){return joinPath(path).split('/').filter(Boolean);}

async function command(input){log($('prompt').textContent+' '+input,'command');history.push(input);historyIndex=history.length;const [raw,...args]=tokenize(input);const cmd=(raw||'').toLowerCase();const p=panes[active];switch(cmd){
 case 'help':log('DIR · CD "folder" · CD .. · USE LEFT|RIGHT · SELECT "name"|* · COPY · PASTE · TRANSFER · UPLOAD · DUPLICATE · DOWNLOAD · ZIP · VIEW · MKDIR "name" · MOUNT LOCAL|DRIVE|SUPABASE|STAGING · CONNECT DRIVE|VAULT · QUEUE · STOP · CLS · VER');log('COPY stores a selection; PASTE or TRANSFER opens a destination review. ↑/↓ recalls commands. Tab completes a filename.');break;
 case 'dir':case 'ls':await refresh(active);log(p.entries.length?p.entries.map(e=>(e.directory?'<DIR>':bytes(e.bytes).padStart(9))+'  '+e.name).join('\n'):'Directory empty.');break;
 case 'cd':if(!p.provider)throw Error('Mount a location first.');if(!args.length){log('/'+p.path);break;}if(args[0]==='..'){await navigate(active,parentPath(p.path));break;}let e=p.entries.find(e=>e.directory&&e.name.toLowerCase()===args.join(' ').toLowerCase());if(!e)throw Error('Folder not found. Use DIR to list available folders.');await navigate(active,await p.provider.enter(e,p.path));break;
 case 'use':if(!['left','right'].includes(args[0]?.toLowerCase()))throw Error('USE LEFT or USE RIGHT');active=args[0].toLowerCase()==='left'?0:1;updateActive();break;
 case 'select':if(args[0]==='*')p.entries.forEach(e=>p.selected.add(e.id));else{const e=p.entries.find(e=>e.name.toLowerCase()===args.join(' ').toLowerCase());if(!e)throw Error('File or folder not found.');p.selected.add(e.id);}renderPane(active);log(p.selected.size+' items selected.');break;
 case 'copy':clipboard=requireSelected();updateActive();log(clipboard.entries.length+' items on NightCopy clipboard. Choose a destination and PASTE.');break;
 case 'paste':if(!clipboard)throw Error('COPY a selection first.');await prepare('transfer',clipboard,snapshot(panes[active]));break;
 case 'transfer':case 'xcopy':await prepare('transfer');break;
 case 'upload':if(!['drive','supabase'].includes(panes[1-active].provider?.kind))throw Error('Choose Google Drive or Supabase in the destination pane first.');await prepare('transfer');break;
 case 'duplicate':case 'dup':await prepare('duplicate');break;
 case 'download':await prepare('download');break;
 case 'zip':{const s=requireSelected();await prepare('zip',s,panes[1-active].provider?snapshot(panes[1-active]):{provider:staging,path:''});break;}
 case 'view':await preview();break;
 case 'mkdir':await newFolder(args.join(' '));break;
 case 'mount':await mount(active,args[0]?.toLowerCase());break;
 case 'connect':if(args[0]?.toLowerCase()==='drive')await c.connectDrive();else setView('connections');break;
 case 'queue':setView('queue');log(jobs.length+' operation(s); '+jobs.filter(j=>j.status==='running').length+' running.');break;
 case 'stop':for(const j of jobs)if(['queued','running'].includes(j.status)){j.controller.abort();if(j.status==='queued'){j.status='stopped';j.message='Stopped before transfer started';}}renderJobs();log('Stop requested. Completed files remain at destination.');break;
 case 'cls':case 'clear':logs.length=0;renderLog();break;
 case 'ver':log('NIGHTCOPY v2.0 / ColeTech Systems / Browser filesystem + HTTPS cloud transports.');break;
 case '':break;
 default:throw Error('Unknown command: '+cmd+'. Type HELP for available commands.');
}}

document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>setView(b.dataset.view));
document.querySelectorAll('[data-mount]').forEach(b=>b.onclick=guard(()=>mount(active,b.dataset.mount)));
$('uploadFiles').onclick=chooseFiles;$('filePicker').onchange=guard(e=>imported([...e.target.files]));$('folderPicker').onchange=guard(e=>imported([...e.target.files]));
$('connectDrive').onclick=guard(async()=>{if(c.driveToken)await mount(1,'drive');else{setView('connections');await c.connectDrive();if(c.driveToken){await mount(1,'drive');setView('files');}}});
$('driveLogin').onclick=guard(async()=>{await c.connectDrive();if(c.driveToken){await mount(1,'drive');setView('files');}});
$('driveDisconnect').onclick=()=>{c.driveToken=null;c.driveUser=null;for(const p of panes)if(p.provider?.kind==='drive'){p.entries=[];p.selected.clear();p.error='Drive disconnected.';}renderConnections();panes.forEach((p,i)=>renderPane(i));log('Drive disconnected. No Google credentials retained.');};
$('accountButton').onclick=()=>setView('connections');$('mountLocal').onclick=guard(()=>mount(active,'local'));
document.addEventListener('click',guard(async e=>{const picker=e.target.closest('[data-picker]');if(picker)chooseLocation(Number(picker.dataset.picker));if(e.target.closest('[data-import]'))chooseFiles();if(e.target.closest('[data-setup]'))setView('connections');if(e.target.closest('[data-show-files]'))setView('files');const stop=e.target.closest('[data-stop]');if(stop){const j=jobs.find(j=>j.id===stop.dataset.stop);j.controller.abort();if(j.status==='queued'){j.status='stopped';j.message='Stopped before transfer started';}renderJobs();}}));
for(let i=0;i<2;i++){$('provider'+i).onchange=guard(e=>mount(i,e.target.value));$('filter'+i).oninput=()=>renderPane(i);$('all'+i).onchange=e=>{active=i;for(const f of panes[i].entries.filter(f=>f.name.toLowerCase().includes($('filter'+i).value.toLowerCase())))e.target.checked?panes[i].selected.add(f.id):panes[i].selected.delete(f.id);renderPane(i);};$('pane'+i).addEventListener('click',guard(async e=>{active=i;updateActive();const check=e.target.closest('[data-check]');if(check){check.checked?panes[i].selected.add(check.dataset.check):panes[i].selected.delete(check.dataset.check);renderPane(i);return;}const open=e.target.closest('[data-open]');if(open)await openEntry(i,open.dataset.open);}));document.querySelector('[data-up="'+i+'"]').onclick=guard(()=>navigate(i,parentPath(panes[i].path)));$('pane'+i).addEventListener('dragover',e=>{e.preventDefault();$('pane'+i).classList.add('dragging');});$('pane'+i).addEventListener('dragleave',()=>$('pane'+i).classList.remove('dragging'));$('pane'+i).addEventListener('drop',guard(async e=>{e.preventDefault();$('pane'+i).classList.remove('dragging');await imported([...e.dataTransfer.files]);}));}
$('swapPanes').onclick=async()=>{[panes[0],panes[1]]=[panes[1],panes[0]];active=1-active;for(let i=0;i<2;i++){refreshSerial[i]++;renderPane(i);}log('Left and right volumes swapped.');};$('refreshPanes').onclick=guard(()=>Promise.all([refresh(0),refresh(1)]));
$('copyButton').onclick=guard(()=>{clipboard=requireSelected();updateActive();log(clipboard.entries.length+' items copied to clipboard.');notify('Copied selection. Paste into the active folder.');});
$('pasteButton').onclick=guard(()=>prepare('transfer',clipboard,snapshot(panes[active])));$('transferButton').onclick=guard(()=>prepare('transfer'));$('duplicateButton').onclick=guard(()=>prepare('duplicate'));$('downloadButton').onclick=guard(()=>prepare('download'));$('zipButton').onclick=guard(()=>prepare('zip',requireSelected(),panes[1-active].provider?snapshot(panes[1-active]):{provider:staging,path:''}));$('folderButton').onclick=guard(()=>newFolder());
$('clearJobs').onclick=()=>{for(let i=jobs.length-1;i>=0;i--)if(!['queued','running'].includes(jobs[i].status))jobs.splice(i,1);renderJobs();};
document.querySelectorAll('[data-location]').forEach(b=>b.onclick=guard(async()=>{$('locationDialog').close();await mount(pickerSide,b.dataset.location);}));$('importFolder').onclick=()=>{$('locationDialog').close();$('folderPicker').click();};$('closeLocation').onclick=()=>$('locationDialog').close();$('closePreview').onclick=()=>$('previewDialog').close();$('previewDialog').addEventListener('close',()=>{if(previewUrl){URL.revokeObjectURL(previewUrl);previewUrl=null;}$('previewContent').replaceChildren();});
$('loginForm').onsubmit=guard(async e=>{e.preventDefault();$('sbLogin').disabled=true;try{await c.login($('loginEmail').value,$('loginPassword').value);$('loginPassword').value='';await mount(1,'supabase');setView('files');}finally{$('sbLogin').disabled=false;}});
$('logoutButton').onclick=guard(async()=>{await c.logout();for(let i=0;i<2;i++)if(panes[i].provider?.kind==='supabase'){panes[i].selected.clear();await refresh(i);}log('Supabase signed out.');});
$('settingsForm').onsubmit=guard(async e=>{e.preventDefault();const url=$('settingUrl').value.replace(/\/$/,'');if(new URL(url).protocol!=='https:'||!new URL(url).hostname.endsWith('.supabase.co'))throw Error('Use an HTTPS supabase.co project URL.');const key=$('settingKey').value.trim();if(key.startsWith('sb_secret_'))throw Error('Use a public key. Secret/service-role keys cannot be used here.');if(key.split('.').length===3){try{const claim=JSON.parse(atob(key.split('.')[1].replaceAll('-','+').replaceAll('_','/')));if(claim.role!=='anon')throw Error('Use the anon public key.');}catch(e){throw Error('Invalid public anon key.');}}const google=$('settingGoogle').value.trim();if(google&&!/^[a-zA-Z0-9-]+\.apps\.googleusercontent\.com$/.test(google))throw Error('Use a Google web OAuth client ID ending in apps.googleusercontent.com.');config={...config,supabaseUrl:url,supabaseKey:key,bucket:$('settingBucket').value.trim(),googleClientId:google,driveAccount:$('settingAccount').value.trim()};localStorage.setItem('nightcopy-settings',JSON.stringify(config));c.subscription?.unsubscribe();c.sb?.auth.stopAutoRefresh();c=new Connections(config,renderConnections);for(const p of panes)if(['drive','supabase'].includes(p.provider?.kind)){p.provider=null;p.path='';p.entries=[];p.selected.clear();}panes.forEach((p,i)=>renderPane(i));try{await c.init();log('Supabase public connection verified.');notify('Settings saved. Project connected.');}catch(e){renderConnections();throw e;}});
$('terminalForm').onsubmit=guard(async e=>{e.preventDefault();const input=$('commandInput').value;$('commandInput').value='';await command(input);});
$('commandInput').onkeydown=e=>{if(e.key==='ArrowUp'){e.preventDefault();historyIndex=Math.max(0,historyIndex-1);e.target.value=history[historyIndex]||'';}else if(e.key==='ArrowDown'){e.preventDefault();historyIndex=Math.min(history.length,historyIndex+1);e.target.value=history[historyIndex]||'';}else if(e.key==='Tab'){e.preventDefault();const match=e.target.value.match(/^(\S+\s+)(.*)$/);if(match){const prefix=match[2].replace(/^"/,'').toLowerCase();const candidate=panes[active].entries.find(e=>e.name.toLowerCase().startsWith(prefix));if(candidate)e.target.value=match[1]+'"'+candidate.name+'"';}}};
$('terminalClear').onclick=()=>{logs.length=0;renderLog();};$('terminalHelp').onclick=$('helpButton').onclick=guard(()=>command('help'));$('collapseTerminal').onclick=()=>{const hidden=$('terminalBody').hidden=!$('terminalBody').hidden;$('collapseTerminal').textContent=hidden?'+':'−';$('collapseTerminal').setAttribute('aria-expanded',String(!hidden));};
document.addEventListener('keydown',guard(async e=>{if(e.target.matches('input,select,textarea')||document.querySelector('dialog[open]'))return;if(e.key==='F5'){e.preventDefault();$('copyButton').click();}else if(e.key==='F6'){e.preventDefault();await prepare('transfer');}else if(e.key==='F3'){e.preventDefault();await preview();}else if(e.key==='Tab'&&!e.ctrlKey&&!e.altKey&&!e.metaKey&&e.target===document.body){e.preventDefault();active=1-active;updateActive();}else if(e.key==='/'){e.preventDefault();$('filter'+active).focus();}else if(e.ctrlKey&&e.key==='`'){$('commandInput').focus();}}));
for(const [id,key]of [['settingUrl','supabaseUrl'],['settingKey','supabaseKey'],['settingBucket','bucket'],['settingGoogle','googleClientId'],['settingAccount','driveAccount']])$(id).value=config[key]||'';
function clock(){$('clock').textContent=new Date().toLocaleTimeString('en-GB');}clock();setInterval(clock,1000);$('hostLabel').textContent=location.hostname.startsWith('127.')||location.hostname==='localhost'?'LOCAL PREVIEW':location.hostname;
renderJobs();await refresh(0);renderPane(1);log('NIGHTCOPY v2.0 / ColeTech Systems');log('Local staging ready. Mount a folder or connect a cloud volume. Type HELP.','success');
try{await c.init();if(c.settings)log('Supabase project reachable. Sign in to mount your private vault.','success');}catch(e){log(e.message,'error');}renderConnections();
