import {createClient} from '@supabase/supabase-js';
import {joinPath,pathParts,copyName,sortEntries,checkAbort,nativeExports} from './core.js';

const authStorage={getItem:k=>localStorage.getItem(k),removeItem:k=>localStorage.removeItem(k),setItem(k,v){try{const s=JSON.parse(v);delete s.provider_token;delete s.provider_refresh_token;v=JSON.stringify(s);}catch{}localStorage.setItem(k,v);}};
export class Connections {
 constructor(config,onChange){this.config=config;this.onChange=onChange;this.driveToken=null;this.driveUser=null;this.session=null;this.settings=null;this.storageReady=false;}
 async init(){
  if(!this.config.supabaseUrl||!this.config.supabaseKey)return;
  this.sb=createClient(this.config.supabaseUrl,this.config.supabaseKey,{auth:{flowType:'pkce',storage:authStorage,storageKey:'nightcopy-auth-'+new URL(this.config.supabaseUrl).hostname,detectSessionInUrl:true}});
  const listener=this.sb.auth.onAuthStateChange((event,session)=>{this.session=session;if(session?.provider_token)this.pendingDriveToken=session.provider_token;if(event==='SIGNED_OUT'){this.driveToken=null;this.driveUser=null;this.storageReady=false;}this.onChange();});this.subscription=listener.data.subscription;
  const r=await fetch(this.config.supabaseUrl+'/auth/v1/settings',{headers:{apikey:this.config.supabaseKey}});
  const data=await r.json();if(!r.ok)throw Error('Supabase connection rejected. Update the public key in Connections.');this.settings=data;
  const {data:auth,error}=await this.sb.auth.getSession();if(error)throw error;this.session=auth.session;
  if(this.pendingDriveToken){await this.acceptDriveToken(this.pendingDriveToken);this.pendingDriveToken=null;}
  this.onChange();
 }
 async login(email,password){if(!this.sb||!this.settings)throw Error('Configure a valid Supabase connection first.');const {error}=await this.sb.auth.signInWithPassword({email,password});if(error)throw error;}
 async logout(){this.driveToken=null;this.driveUser=null;this.pendingDriveToken=null;if(this.sb){const {error}=await this.sb.auth.signOut();if(error)throw error;}this.onChange();}
 async acceptDriveToken(token){const r=await fetch('https://www.googleapis.com/drive/v3/about?fields=user,storageQuota',{headers:{Authorization:'Bearer '+token}});if(!r.ok)throw Error('Google Drive authorization expired or was denied. Connect again.');const profile=await r.json();if(profile.user.emailAddress.toLowerCase()!==this.config.driveAccount.toLowerCase())throw Error('Select '+this.config.driveAccount+' in Google sign-in.');this.driveToken=token;this.driveUser=profile.user;this.quota=profile.storageQuota;this.onChange();}
 async connectDrive(){
  if(this.config.googleClientId){
   if(!window.google?.accounts?.oauth2)await new Promise((resolve,reject)=>{let s=document.createElement('script');s.src='https://accounts.google.com/gsi/client';s.onload=resolve;s.onerror=()=>reject(Error('Google sign-in could not load.'));document.head.append(s);});
   return new Promise((resolve,reject)=>{const client=window.google.accounts.oauth2.initTokenClient({client_id:this.config.googleClientId,scope:'https://www.googleapis.com/auth/drive',hint:this.config.driveAccount,callback:r=>{if(r.error)return reject(Error(r.error_description||r.error));this.acceptDriveToken(r.access_token).then(resolve,reject);},error_callback:r=>reject(Error(r.type==='popup_closed'?'Google sign-in was closed.':r.type))});client.requestAccessToken({prompt:'select_account'});});
  }
  if(!this.settings?.external?.google)throw Error('Add a Google OAuth client ID in Connections, or enable Google sign-in in Supabase.');
  const {error}=await this.sb.auth.signInWithOAuth({provider:'google',options:{redirectTo:location.origin+'/',scopes:'https://www.googleapis.com/auth/drive',queryParams:{login_hint:this.config.driveAccount,prompt:'select_account consent'}}});if(error)throw error;
 }
 async drive(path,init={}){if(!this.driveToken)throw Error('Connect Google Drive first.');const r=await fetch('https://www.googleapis.com/drive/v3/'+path,{...init,headers:{Authorization:'Bearer '+this.driveToken,...init.headers}});if(r.status===401){this.driveToken=null;this.driveUser=null;this.onChange();throw Error('Google session expired. Connect Drive again.');}if(!r.ok){const d=await r.json().catch(()=>({}));throw Error(d.error?.message||'Google Drive request failed ('+r.status+').');}return r;}
}

export class MemoryProvider {
 constructor(){this.kind='staging';this.label='LOCAL STAGING';this.files=new Map();this.dirs=new Set(['']);this.writable=true;}
 async list(path=''){const prefix=path?path+'/':'';const results=new Map();for(const d of this.dirs){if(d.startsWith(prefix)&&d!==path){const name=d.slice(prefix.length).split('/')[0];results.set(name,{id:joinPath(path,name),name,directory:true,bytes:0});}}for(const [p,f] of this.files){if(!p.startsWith(prefix))continue;const name=p.slice(prefix.length).split('/')[0];if(p.slice(prefix.length).includes('/'))results.set(name,{id:joinPath(path,name),name,directory:true,bytes:0});else results.set(name,{id:p,name,directory:false,bytes:f.size,modified:f.lastModified});}return sortEntries([...results.values()]);}
 async read(entry,signal){checkAbort(signal);const f=this.files.get(entry.id);if(!f)throw Error('File is no longer in this session.');return {blob:f,name:entry.name};}
 async write(path,name,blob,signal,onProgress){checkAbort(signal);let target=joinPath(path,name);for(let n=1;this.files.has(target)||this.dirs.has(target);n++)target=joinPath(path,copyName(name,n));const f=new File([blob],target.split('/').at(-1),{type:blob.type});this.files.set(target,f);this.dirs.add(path);onProgress?.(blob.size,blob.size);return {name:f.name,path:target};}
 async mkdir(path,name){const p=joinPath(path,name);if(this.files.has(p))throw Error('A file already uses that folder name.');this.dirs.add(p);return p;}
 async enter(entry){return entry.id;}
 import(files){for(const f of files){let p=joinPath(f.webkitRelativePath||f.name);if(this.files.has(p)){const base=p.split('/').slice(0,-1).join('/');let n=1;while(this.files.has(p))p=joinPath(base,copyName(f.name,n++));}this.files.set(p,f);const bits=pathParts(p);for(let i=1;i<bits.length;i++)this.dirs.add(bits.slice(0,i).join('/'));}}
}

export class LocalProvider {
 constructor(handle){this.kind='local';this.label=handle.name.toUpperCase();this.handle=handle;this.writable=true;}
 async dir(path,create=false){let h=this.handle;for(const part of pathParts(path))h=await h.getDirectoryHandle(part,{create});return h;}
 async list(path=''){const h=await this.dir(path);const rows=[];for await(const [name,entry]of h.entries()){if(rows.length>=10000)throw Error('Folder has more than 10,000 entries. Choose a smaller folder.');const f=entry.kind==='file'?await entry.getFile():null;rows.push({id:joinPath(path,name),name,directory:!f,bytes:f?.size||0,modified:f?.lastModified,handle:entry});}return sortEntries(rows);}
 async read(e,signal){checkAbort(signal);return {blob:await e.handle.getFile(),name:e.name};}
 async write(path,name,blob,signal,onProgress){checkAbort(signal);const dir=await this.dir(path);let candidate=name;for(let n=1;;n++){try{await dir.getFileHandle(candidate);candidate=copyName(name,n);continue;}catch(e){if(e.name!=='NotFoundError'&&e.name!=='TypeMismatchError')throw e;if(e.name==='TypeMismatchError'){candidate=copyName(name,n);continue;}}try{await dir.getDirectoryHandle(candidate);candidate=copyName(name,n);}catch(e){if(e.name==='NotFoundError')break;if(e.name!=='TypeMismatchError')throw e;candidate=copyName(name,n);}}
  const handle=await dir.getFileHandle(candidate,{create:true});const stream=await handle.createWritable();let done=0;try{for(let offset=0;offset<blob.size;offset+=4*1024*1024){checkAbort(signal);const chunk=blob.slice(offset,offset+4*1024*1024);await stream.write(chunk);done+=chunk.size;onProgress?.(done,blob.size);}checkAbort(signal);await stream.close();}catch(e){await stream.abort().catch(()=>{});throw e;}return {name:candidate,path:joinPath(path,candidate)};
 }
 async mkdir(path,name){await this.dir(joinPath(path,name),true);return joinPath(path,name);}
 async enter(entry){return entry.id;}
}

export class SupabaseProvider {
 constructor(connections){this.kind='supabase';this.label='SUPABASE VAULT';this.c=connections;this.writable=true;}
 root(path=''){if(!this.c.session)throw Error('Sign in to Supabase first.');return joinPath(this.c.session.user.id,path);}
 store(){if(!this.c.settings)throw Error('Update the Supabase connection first.');return this.c.sb.storage.from(this.c.config.bucket);}
 async list(path=''){const all=[];for(let offset=0;;offset+=1000){const {data,error}=await this.store().list(this.root(path),{limit:1000,offset,sortBy:{column:'name',order:'asc'}});if(error){this.c.storageReady=false;this.c.onChange();throw Error(error.message+' — check the NightCopy private bucket and policies.');}all.push(...data);if(data.length<1000)break;if(all.length>=10000)throw Error('Folder listing exceeds 10,000 entries.');}this.c.storageReady=true;this.c.onChange();return sortEntries(all.filter(x=>x.name!=='.nightcopy-folder').map(x=>({id:joinPath(path,x.name),name:x.name,directory:!x.id,bytes:x.metadata?.size||0,modified:x.updated_at})));}
 async read(entry,signal){checkAbort(signal);const {data,error}=await this.c.sb.auth.getSession();if(error||!data.session)throw Error('Sign in to Supabase first.');const c=this.c.config;const path=this.root(entry.id).split('/').map(encodeURIComponent).join('/');const r=await fetch(c.supabaseUrl+'/storage/v1/object/authenticated/'+encodeURIComponent(c.bucket)+'/'+path,{headers:{apikey:c.supabaseKey,Authorization:'Bearer '+data.session.access_token},signal});if(!r.ok)throw Error('Vault download failed ('+r.status+').');return {blob:await boundedBlob(r,c.maxBufferedBytes,signal),name:entry.name};}
 async write(path,name,blob,signal,onProgress){const key=this.root(joinPath(path,name));const sbSession=await this.c.sb.auth.getSession();if(sbSession.error||!sbSession.data.session)throw Error('Supabase session expired. Sign in again.');const c=this.c.config;
  const uri=c.supabaseUrl+'/storage/v1/object/'+encodeURIComponent(c.bucket)+'/'+key.split('/').map(encodeURIComponent).join('/');
  try{await xhrUpload(uri,'POST',blob,{apikey:c.supabaseKey,Authorization:'Bearer '+sbSession.data.session.access_token,'x-upsert':'false','Content-Type':blob.type||'application/octet-stream'},signal,onProgress);}catch(e){if(e.status===409||e.status===400&&/already exists|duplicate/i.test(e.message)){for(let n=1;n<1000;n++){const candidate=copyName(name,n);if(!(await this.list(path)).some(x=>x.name===candidate))return this.write(path,candidate,blob,signal,onProgress);}}throw e;}return {name,path:joinPath(path,name)};
 }
 async mkdir(path,name){const dest=joinPath(path,name);const {error}=await this.store().upload(this.root(dest+'/.nightcopy-folder'),new Blob(['']),{upsert:false});if(error&&!/already exists/i.test(error.message))throw error;return dest;}
 async enter(e){return e.id;}
}

export class DriveProvider {
 constructor(connections){this.kind='drive';this.label='GOOGLE DRIVE';this.c=connections;this.writable=true;this.folders=new Map([['','root']]);}
 async list(path=''){const folder=this.folders.get(path);if(!folder)throw Error('Re-open that Drive folder.');const rows=[];let token='';do{const q=new URLSearchParams({q:`'${folder.replaceAll("'","\\'")}' in parents and trashed = false`,fields:'nextPageToken,files(id,name,mimeType,size,modifiedTime,capabilities)',pageSize:'1000'});if(token)q.set('pageToken',token);const r=await this.c.drive('files?'+q);const data=await r.json();rows.push(...data.files);token=data.nextPageToken;if(rows.length>10000)throw Error('Folder listing exceeds 10,000 entries.');}while(token);return sortEntries(rows.map(x=>({id:x.id,name:x.name,directory:x.mimeType==='application/vnd.google-apps.folder',mime:x.mimeType,bytes:Number(x.size)||0,modified:x.modifiedTime,downloadable:x.capabilities?.canDownload!==false})));}
 async enter(e,path){const p=joinPath(path,e.name);this.folders.set(p,e.id);return p;}
 async read(e,signal){if(e.downloadable===false)throw Error('The owner has disabled downloads for '+e.name);if(e.mime?.startsWith('application/vnd.google-apps.')&&!nativeExports[e.mime])throw Error('This Google document type cannot be copied. Open it in Drive.');const exp=nativeExports[e.mime];const r=await this.c.drive('files/'+encodeURIComponent(e.id)+(exp?'/export?mimeType='+encodeURIComponent(exp[0]):'?alt=media'),{signal});const limit=this.c.config.maxBufferedBytes;if(Number(r.headers.get('content-length'))>limit)throw Error('This remote file is too large for the browser buffer. Use the desktop station.');return {blob:await boundedBlob(r,limit,signal),name:e.name+(exp?.[1]||'')};}
 async write(path,name,blob,signal,onProgress){const folder=this.folders.get(path);if(!folder)throw Error('Open a Drive destination first.');const init=await fetch('https://www.googleapis.com/upload/drive/v3/files?uploadType=resumable&fields=id,name,size',{method:'POST',headers:{Authorization:'Bearer '+this.c.driveToken,'Content-Type':'application/json','X-Upload-Content-Type':blob.type||'application/octet-stream','X-Upload-Content-Length':String(blob.size)},body:JSON.stringify({name,parents:[folder] }),signal});if(!init.ok)throw Error('Google upload could not start ('+init.status+').');const url=init.headers.get('Location');if(!url||new URL(url).hostname!=='www.googleapis.com')throw Error('Google returned an invalid upload session.');const result=await xhrUpload(url,'PUT',blob,{'Content-Type':blob.type||'application/octet-stream'},signal,onProgress);return {...result,path:joinPath(path,result.name||name)};}
 async duplicate(e,path,signal){const entries=await this.list(path);let name=copyName(e.name);for(let n=2;entries.some(x=>x.name===name);n++)name=copyName(e.name,n);const r=await this.c.drive('files/'+encodeURIComponent(e.id)+'/copy?fields=id,name',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name,parents:[this.folders.get(path)]}),signal});return r.json();}
 async mkdir(path,name){const r=await this.c.drive('files?fields=id,name',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name,mimeType:'application/vnd.google-apps.folder',parents:[this.folders.get(path)]})});const d=await r.json();const p=joinPath(path,name);this.folders.set(p,d.id);return p;}
}

export async function boundedBlob(response,max,signal){const reader=response.body.getReader();const parts=[];let total=0;try{while(true){checkAbort(signal);const {done,value}=await reader.read();if(done)break;total+=value.length;if(total>max)throw Error('Remote file exceeds the browser buffer limit. Use NightCopy desktop.');parts.push(value);}}finally{await reader.cancel().catch(()=>{});}return new Blob(parts,{type:response.headers.get('Content-Type')||'application/octet-stream'});}
export function xhrUpload(url,method,blob,headers,signal,onProgress){return new Promise((resolve,reject)=>{checkAbort(signal);const xhr=new XMLHttpRequest();xhr.open(method,url);for(const [k,v]of Object.entries(headers))xhr.setRequestHeader(k,v);const abort=()=>xhr.abort();signal?.addEventListener('abort',abort,{once:true});const clean=()=>signal?.removeEventListener('abort',abort);xhr.upload.onprogress=e=>onProgress?.(e.loaded,e.total||blob.size);xhr.onload=()=>{clean();let data;try{data=JSON.parse(xhr.responseText||'{}')}catch{data={}}if(xhr.status<200||xhr.status>=300)return reject(Object.assign(Error(data.error?.message||data.message||data.error||'Upload failed ('+xhr.status+').'),{status:xhr.status}));onProgress?.(blob.size,blob.size);resolve(data);};xhr.onerror=()=>{clean();reject(Error('Upload connection failed. The file may be partial; refresh the destination before retrying.'));};xhr.onabort=()=>{clean();reject(new DOMException('Stopped by operator','AbortError'));};xhr.send(blob);});}
